### ISSUE TITLE
Internal Error with SV Antimatter Cannon

### ISSUE THREAD

**Issue by ABNChaotic** [B-iggy/HWS-Configs#1]
Repeated CoQ errors when selecting the Antimatter cannon in toolbar. 

The M77 Torpedo's CPU Costs seem too high, and the new Railgun seems useless IMO. Does no damage to shields, and 70 damage on combat steel and devices.

![image](https://user-images.githubusercontent.com/68931890/88744661-ff8a6600-d115-11ea-8aa9-bd7d8ef24184.png)

**Comment by B-iggy** [comment]
Oh, someone is following my progress! Thanks for the notice!
The commit yesterday was a heavy work in progress. Didn't think someone is following me. Will take more care now.
I pushed a fix now. Balancing will come at the end, maybe with your help.
