### ISSUE TITLE
SV Torpedos

### ISSUE THREAD

**Issue by stevepaul1982** [B-iggy/HWS-Configs#3]
Am i reading the Itemsconfig.ecf correctly that these will have 500 range on planet? Won't this allow them to kill bases from out of weapons range?  This would essentially make it impossible to use bases in PVP playfields, as you can't sit there to defend them 24/7.

**Comment by B-iggy** [comment]
No, you can't just read plain values from the config and interpolate things from that.
The range is affected by the Atmosphere Density. 500 Range would only be the case on planets with 0.00 Density. There is no planet that have that.
On GG for example it is like in the screenshot.
You are attacked way before 
![image](https://user-images.githubusercontent.com/7815434/89312381-7d4ef400-d677-11ea-8243-cf2f2fbd63b4.png)

**Comment by stevepaul1982** [comment]
Thanks Rex - makes perfect sense.
