### ISSUE TITLE
Red CV thrusters HP issue

### ISSUE THREAD

**Issue by Politary** [B-iggy/HWS-Configs#4]
- Red CV thrusters HP needs a drastic boost. They should be able to take at least 3 manual shots, ideally 4-5 before getting destroyed.

They get one shotted by manual fire strike, and since a build can have only 2 red thrusters in one direction due to CPU, it makes them not viable compared to blue thrusters, where for one red thruster you can put 5 blue ones, each of which takes same one manual strike.

As a comparison, turrets on hws have 6-7x the hp of vanilla turrets. While red thruster HP is the same

**Comment by B-iggy** [comment]
Ok, and why overall? You just mention stats and "make it so" but why would it benefit the gameplay?

Turret HP boost, Damage / EWS changes and HWS Shields were done for quicker, satisfying fights - IF you have EWS etc. in mind. Strategy, Positioning and Skill should matter.
Making Thrusters extremely tanky would shift all of the above away and enemies can flee whenever they want again.

My 3 thoughts:
- IF we activate Exposed Thrusters one day, that would be required of course. 
- To help some workshop noobies, more HP for thrusters help too.
- I hate it if things don't make sense or are useless. The whole idea behind EWS. Even Pistols on HWS are in specific situations the way to go. So a rebalancement of Thrusters would be a consequence too I think.
I checked / compared couple of stats and they seem to me totally random. They are not put into relation. There is no decision for players to make. Overall nothing competitive.

**Comment by Politary** [comment]
There is no reason to use Red thrusters. Blue ones give more surivability since you can have more of them, and very similar thrust/mass stats. This change will only help with occasional shots/lagshots that could kill half of ship's thrust for no reason, direct turret fire or consecutive manual fire on exposed thruster will still kill them quickly.

**Comment by IceDrugg** [comment]
Red XLs are totally OK, i always use them. It's very easy to add armor and lagshot protection around them. If you know how to build, of course.
Rex, you shouldn't change the config in the mercenary interests of one person.

**Comment by Politary** [comment]
"I use them therefore they are good" is not a good argument. I'm saying that they are underpowered and in my previous message i stated why. I have builds with both and can adapt either way.

**Comment by IceDrugg** [comment]
Seems like you got big problems with simple calculations or/and with something else.
CPU: 1 XL (533600) = 4 L (4 x 13340).
HP: XL = 5.6 L
Force: XL = 4.8 L
Size: 1 XL (54 cubes) and 4 L (64 cubes), so XL is more compact (10 cubes).

As you can see it's already better in all stats, no need to make it more better.

**Comment by Politary** [comment]
That would've been true, and it's true in base game. On HWS their hp difference is almost neglected because of overall damage boosts. So L thruster= one shot, 4 L thrusters = 4 shots. One XL thruster = one shot. The same problem Combat steel used to have before. The damage is too high for hp to make any difference.

**Comment by IceDrugg** [comment]
Use "Thruster S" and be happy. It's 100 shots in your logic.
No need to do XL Thrusters harder that couple of armor blocks.

**Comment by Politary** [comment]
Compare thruster S force to thruster L. And Then L to XL. Making them strong as *couple* of armor blocks is my original idea. Right now they are a one shot.

**Comment by IceDrugg** [comment]
The only significant limit is CPU limit. So I'm leveling by CPU values only.
Devices are not armor blocks and they shouldn't tank massive fire. Armor should. XLs HP is OK.

**Comment by Politary** [comment]
One XL's survivability is virtually the same as one L. By using L thrusters you can get -20% force, +20% ocupied space... and 4x the survivability, which doesn't make sense.

**Comment by IceDrugg** [comment]
Playing games makes no sense, you know.
CV Flak Turret is very effective against thrusters. So 10 shots deal large damage. And you wanna tank 40-50 flak shots? How many HP XLs should have, 10 millions maybe?

**Comment by Politary** [comment]
Try hitting CV thruster with a 4x rocket launchers strike and see yourself.

**Comment by IceDrugg** [comment]
No need to do it for me, I've disabled and destroyed enough CVs during my gameplay.
Its you who are dissatisfied with something. Suggest a value to have something to discuss.

**Comment by Politary** [comment]
So you didn't even test it on most recent config? Cool.

**Comment by IceDrugg** [comment]
Can you tell me what HP you want for XLs? Still problems with arithmetic count? Can't use calculator?

**Comment by B-iggy** [comment]
I still need more reasons for that change and more input from others.
Until then I'll close this for now (but it's still history tracked, no worry)
