### ISSUE TITLE
Flak turrets are too strong against normal blocks

### ISSUE THREAD

**Issue by Politary** [B-iggy/HWS-Configs#5]
Flak turret = 4000 damage, 4000 explosion damage, 92 rounds per minute, 1.2 km range, greater tracking and projectile speed compared to rocket turret
Rocket turret = 11 000 damage, 5500 explosion damage, 15 rounds per minute,  1.2 km range

There is little reason to use rocket turrets over flak, at least for CV combat. The only 2 upsides of them are shield damage (CV manual pulses and laser/plasma turrets can deal with shields just fine) and 4 blocks explosion radius, which is not useful due to low damage of explosion itself. In previous season flak used to have less range, but 2x the dps of rocket turrets which made it viable. 

To make them balanced, their rate of fire, range and projectile speed should be nerfed (1.05 km , 30 ROF and 1.5x the speed of rockets is my suggestion, considering flak strong homing abilities).

It probably applies to bases too, but i didn't have a chance to test it.

https://www.youtube.com/watch?v=H4ooy79_0hA

**Comment by B-iggy** [comment]
Agreed. Take a look at https://github.com/B-iggy/HWS-Configs/commit/86b6a2c5874e7bae9379b7175390a9a6b416af6d
