### ISSUE TITLE
Unable to craft CV T2 Shields

### ISSUE THREAD

**Issue by Justin42** [B-iggy/HWS-Configs#6]
https://github.com/B-iggy/HWS-Configs/blob/ff0f69520355543a08d16f49dab05ec6cbe8a599/Templates.ecf#L2439

Not sure if this is intended, but it causes much confusion among new players. It also puts them at even further disadvantage when wondering into PVP areas.

Perhaps there is something I have overlooked or some reasoning I'm unaware of, sorry if this is the case.

**Comment by IceDrugg** [comment]
It's Eleon "feature". No idea why do this, bit I personally think it's pretty dumb.
Anyway you got 2 options:
1) upgrade T1 shield to T2 shield via multitool (disabled on HWS)
2) make BP in creative with T2 shield and just spawn it via F2 on HWS (also you can make BP with T2 warp drive if got HWS config installed locally)

There are no ways of fast mass production of T2 shields for now. You just need repeat 1st or 2nd option by cool-down. Some notes: you can do simple BP with core and T2 shield only (2 devices). Also you can't get T2 shied by unmounting it via multitool (which is also dumb), you can actually get it only with HWS egs:recycle command.

**Comment by Justin42** [comment]
> 1. upgrade T1 shield to T2 shield via multitool (_disabled on HWS_)

Since upgrading is disabled, it seems logical to change the config to enable crafting. I referenced the single line in config.

I'm aware of the second method but of course it's very tedious, and many new players will know nothing of this. Also at recycle 5 this is only a 90% chance to return the shield (if I understand that right). It's a way to acquire a shield yes, but it's certainly not a solution to this issue.

**Comment by IceDrugg** [comment]
> it seems logical to change the config
Lol, as I see you are really new to HWS :D

> at recycle 5 this is only a 90% chance to return the shield
It uses "ceil" method, so if you got 9 devices, it's 8.1 and it rounds to 9.

**Comment by Justin42** [comment]
> Lol, as I see you are really new to HWS :D

I've played on HWS since a7.

This github repo and issue is for discussing changes to the configuration. If you don't believe a change is logical in this case, please explain why. If you have nothing to add, then please leave irrelevant discussion out of the issue so that it can be better understood and tracked. Thank you.

**Comment by B-iggy** [comment]
Fixed as of 6716421b6ced3367b67448ff6cebc7a86d3dac00
